apiVersion: v1
kind: Pod
metadata:
        name: myapp-redis
        labels:
                app: myapp
                type: front-end
spec:
        containers:
                - name: nginx-container
                  image: redis
